package com.ipcg.test;

interface ITestInterface{
	// Primitive return/args
	int32 test1(float32 arg1);
	
	// enum return/args
	Enum1 test2(Enum1 arg1);
	
	// TODO struct return/arg
	Struct1 test3(Struct1 arg1);
	
	// TODO Prmitive array return/arg
//	int32[] test4();
	
	// TODO Struct array return/arg
	
	// TODO Enum array return/arg
};
