package com.ipcg.test;

struct Struct1{
	// Primitive field
	string stringField;
	
	// Structure field
	Struct2 structField;
	
	// Enum field
	Enum1 enumField;
	
	// Primitive field array
//	int32[] intArray;
	
	// Structure field array
	// Struct2[] structArray;
	
	// Enumeration field array
	//	Enum1[] enumArray;
	
	//	string[] stringArray;
};
