package com.ipcg.test;

interface TestInterface{
	void test1();
	
	int32 test2();
	
	int32 test3(TestStruct1 arg1);
	
	int32 test3(int32 arg1, boolean arg2, TestStruct1 arg3, float32 arg4, float64 arg5, int64 arg6, string arg7, TestEnum1 arg8);
	
	TestStruct1 test4();
	
	TestEnum1 test5();
};
