package com.ipcg.test;

struct TestStruct1{
	int32 integerField;
	int64 longField;
	float32 floatField;
	float64 doubleField;
	string stringField;
	boolean boolField;
	TestEnum1[] enumField;
	TestStruct2 structField;
};
